### ISSUE TITLE
How do referenceMentions offsets work?

### ISSUE THREAD

**Issue by oyarsa** [neulab/ReviewAdvisor#13]
In the paper contents JSON, under `metadata.referenceMentions`, there are objects with `startOffset` and `endOffset` fields. After some exploration, I was unable to determine what they are offsets of and what they mean. Are those the boundaries of the content in the `context` field? Where? Are they character offsets, or somehow word offsets?

**Comment by yyy-Apple** [comment]
Here is an example
<img width="579" alt="image" src="https://github.com/user-attachments/assets/181ae795-1289-4303-882e-bff2d2ae5859">


In this example, The reference appear at `context[startOffset: endOffset]`, which is "(Hornik, 1991)".

**Comment by oyarsa** [comment]
Oh, thanks. I thought this would be something completely different. I had my mind on locating where the context appeared in the paper to see the surrounding paragraph, but I solved that in other ways.

Thanks for the reply!
