### ISSUE TITLE
您好，怎样获取review所对应的原文句子？

### ISSUE THREAD

**Issue by zhanghaoxuan1999** [neulab/ReviewAdvisor#5]
![1646106718(1)](https://user-images.githubusercontent.com/61461646/156101570-c977be67-dedc-467f-a585-a41a345db35b.jpg)
例如：我想选择the motivation of review 所对应的 原文(paper content)中的句子，我应该如何操作呢？

**Comment by yyy-Apple** [comment]
您好，如果是需要自动抽取与每个aspect对应的原文句子的话，我们可以过几天更新一些代码来实现这一功能。

**Comment by zhanghaoxuan1999** [comment]
> 您好，如果是需要自动抽取与每个aspect对应的原文句子的话，我们可以过几天更新一些代码来实现这一功能。

冒昧打扰您，不知道何时可以获取该数据呢？

**Comment by yyy-Apple** [comment]
非常抱歉，经过讨论，我们暂时不打算公开跟模型有关的代码。我们会在论文被接收之后放出相关代码。
