### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by liuzechao-CCNU** [neulab/ReviewAdvisor#6]
您好，请问数据集文件夹已经下架了，之后会有重新上传的计划吗？或者应该怎么样获取ASAP-Review数据集呢？

**Comment by yyy-Apple** [comment]
您好，这个链接里有我们的数据集文件：https://drive.google.com/file/d/1nJdljy468roUcKLbVwWUhMs7teirah75/view?usp=sharing

**Comment by liuzechao-CCNU** [comment]
thank you
